# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

# variables:
#    tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: windows-2022
    steps:

#     - task: Docker@2
#       displayName: Build an image
#       inputs:
#         command: build
#         dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
#         tags: |
#               $(tag)
#               base-mysql-windows-2022
#     - task: Docker@2
#       inputs:
#         containerRegistry: 'davidgarciavivesdn'
#         repository: 'base-mysql-windows-2022'
#         command: 'push'

    - task: Docker@2
      displayName: Build and push image
      inputs:
        containerRegistry: 'davidgarciavivesdn'
        repository: 'base-mysql-windows-2022'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          base-mysql-windows-2022